name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found."
          fi

      - name: Run Python script
        run: |
          nohup python app.py &  # Menjalankan server di background
          sleep 5  # Tunggu beberapa detik untuk memastikan server berjalan
          
      - name: Check server status
        run: |
          if curl -f http://localhost:5000; then  # Ubah port sesuai dengan yang digunakan dalam app.py
            echo "Server is running."
          else
            echo "Server not running."
          fi
